// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "messagetype", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageIn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageIn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageOut")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageIn.#part")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageOut.#part")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.Message.#segment1(Microsoft.XLANGs.Core.StopConditions)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "messagetype", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageIn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "messagetype", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageOut")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "ctx", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageIn.#.ctor(System.String,Microsoft.XLANGs.Core.Context)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "ctx", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageOut.#.ctor(System.String,Microsoft.XLANGs.Core.Context)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__AcmeCorp_BizTalkBuildSample_Schemas_MessageIn__")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageIn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageOut")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations._MODULE_PROXY_")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "messagetype", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageOut")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "MODULE", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations._MODULE_PROXY_")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "PROXY", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations._MODULE_PROXY_")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageIn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__messagetype_AcmeCorp_BizTalkBuildSample_Schemas_MessageOut")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1802:UseLiteralsWhereAppropriate", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.Message.#__execable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "__ctx0__", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.Message+__Message_root_0.#Finally()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.Message.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.Message.#__access")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.Message.#__execable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.Message.#IsExeced")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.MessageInPortType.#__access")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.MessageOutPortType.#__access")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "AcmeCorp.BizTalkBuildSample.Orchestrations.__AcmeCorp_BizTalkBuildSample_Schemas_MessageOut__")]
